### ISSUE TITLE
Critical issue with some of the JS files.

### ISSUE THREAD

**Issue by desugar-64** [GCRC/nunaliit_android#1]
Looks like android system webview is failing at very low level when trying to load one of the nunaliit javascript files. The only `Atlas Loading` text on the blank screen is appearing.
`Logs: E/chromium: [ERROR:BudgetService.cpp(167)] Unable to connect
to the Mojo BudgetService.`
Unfortunately no more informations in my stacktrace. At the moment I found no solution
and also no more informations.
Device: Google Pixel 2 XL
Android 8.1.0

**Comment by ahayes** [comment]
No longer an issue.
