### ISSUE TITLE
UI to filter and sort document list

### ISSUE THREAD

**Issue by ahayes** [GCRC/nunaliit_android#45]
Filter based on:
- Schema
- Created on device

Sort:
- Alphabetically (forward & reverse)
- Chronologically (forward & reverse)
- Proximity (nearest to me geographically - leave out docs without nunaliit_geom)

**Comment by jpfiset** [comment]
In mobile app, the DocumentDb already contains a view to select documents based on schema
--- viewNunaliitSchema [DocumentDb:79]
--- Should be able to create filter based on this view
--- designDoc.queryView({viewName: 'nunaliit-schema',keys: ['module']...})
