### ISSUE TITLE
While adding related media, displayed document is still visible

### ISSUE THREAD

**Issue by jpfiset** [GCRC/nunaliit_android#49]
Reproduce:
- Select document from main list
- Press "Add Related Media" and select a schema

The dialog with a new related media appears. Yet, the current document is still visible with all the buttons. Pressing on the buttons associated with the displayed document still function and leads to confusion.

**Comment by grrrian** [comment]
Fixed in commit sha: 468b12a3b3d1dd45884470babf3c09bba699a6df.
