### ISSUE TITLE
When uploading documents to server, keys nunaliit_mobile_attachments and nunaliit_mobile_needs_new_location are left

### ISSUE THREAD

**Issue by jpfiset** [GCRC/nunaliit_android#50]
When a document is uploaded to the server (submission database), some of the keys used internally to manage document editing are left and find their way to the live database. These keys are:
- nunaliit_mobile_attachments
- nunaliit_mobile_needs_new_location

**Comment by ThomasHEaton** [comment]
https://github.com/GCRC/nunaliit_android/pull/56
