### ISSUE TITLE
Editing a document erases previous attachments

### ISSUE THREAD

**Issue by jpfiset** [GCRC/nunaliit_android#51]
At this time, I do not have step by step instructions to reproduce this. However, from code review, it appears that if a document that previously contained attachments (from server), the logic during editing would deleted the "nunaliit_attachments" key, effectively removing them from the document.

Re: n2.couchEdit.js:1480 in _save() function

**Comment by grrrian** [comment]
Thanks for noticing this! We were actually preventing document editing if new attachments were not added. This has been fixed: we can now edit media documents and preserve existing attachments.

**Comment by grrrian** [comment]
Thanks for noticing this! We were actually preventing document editing if new attachments were not added. This has been fixed: we can now edit media documents and preserve existing attachments.
