### ISSUE TITLE
Use inline version of nunaliit library for debug builds

### ISSUE THREAD

**Issue by ahayes** [GCRC/nunaliit_android#53]
The app should be updated to use the standard nunaliit JS for production builds and the new "inline" debug version for debug builds to avoid document.write() issues in the classic debug version of the JS library.

See https://github.com/GCRC/nunaliit/issues/725

**Comment by grrrian** [comment]
It should be noted that I did not find a way to create a production build. This PR simply replaced the index.html to use the inline debug version. @ahayes please let me know if a production build is currently supported.
